import json
import logging
import re
from typing import Any, Dict, List, Optional

import httpx

from app.ai.prompts import (
    EXPLANATION_PROMPT,
    JOB_EXTRACTION_PROMPT,
    QUERY_EXPANSION_PROMPT,
    RESUME_EXTRACTION_PROMPT,
)
from app.ai.structured_outputs import (
    ExtractedCandidateProfile,
    ExtractedEducation,
    ExtractedExperience,
    ExtractedJobData,
    ExtractedProject,
    ExtractedRequirement,
    GroundedExplanation,
)
from app.core.config import settings

logger = logging.getLogger(__name__)

GEMINI_GENERATE_URL = (
    "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
)


class LLMClient:
    """
    LLM Client interfacing with Google Gemini 2.5 Flash for JSON-structured outputs,
    information extraction, query expansion, and grounded explainability generation.
    """

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or settings.google_api_key
        self._query_expansion_cache: Dict[str, List[str]] = {}

    def _call_gemini_json(self, prompt: str, temperature: float = 0.1) -> Dict[str, Any]:
        """Calls Gemini API with JSON mode and returns parsed dictionary."""
        if not self.api_key:
            raise ValueError("GOOGLE_API_KEY is not configured.")

        url = f"{GEMINI_GENERATE_URL}?key={self.api_key}"
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": temperature,
                "responseMimeType": "application/json",
            },
        }

        with httpx.Client(timeout=30.0) as client:
            response = client.post(url, json=payload)
            if response.status_code != 200:
                raise RuntimeError(
                    f"Gemini API returned status {response.status_code}: {response.text[:200]}"
                )

            data = response.json()
            candidates = data.get("candidates", [])
            if not candidates:
                raise RuntimeError("No candidate response generated by Gemini.")

            raw_text = candidates[0].get("content", {}).get("parts", [{}])[0].get("text", "")
            return json.loads(raw_text)

    def extract_job_data(self, jd_text: str) -> ExtractedJobData:
        """Extracts structured job title, summary, and decomposed atomic requirements."""
        prompt = JOB_EXTRACTION_PROMPT.replace("{text}", jd_text[:6000])

        try:
            result_json = self._call_gemini_json(prompt)
            return ExtractedJobData(**result_json)
        except Exception as e:
            logger.warning(f"LLM job extraction failed, using fallback heuristic: {e}")
            return self._fallback_job_extraction(jd_text)

    def extract_candidate_profile(self, resume_text: str) -> ExtractedCandidateProfile:
        """Extracts structured candidate profile, experience, skills, projects, and education."""
        prompt = RESUME_EXTRACTION_PROMPT.replace("{text}", resume_text[:7000])

        try:
            result_json = self._call_gemini_json(prompt)
            return ExtractedCandidateProfile(**result_json)
        except Exception as e:
            logger.warning(f"LLM candidate extraction failed, using fallback heuristic: {e}")
            return self._fallback_candidate_extraction(resume_text)

    def expand_query(self, requirement: str) -> List[str]:
        """Expands a single requirement into synonyms and related technical keywords."""
        cache_key = requirement.strip().lower()
        if cache_key in self._query_expansion_cache:
            return self._query_expansion_cache[cache_key]

        prompt = QUERY_EXPANSION_PROMPT.replace("{requirement}", requirement)

        try:
            result_json = self._call_gemini_json(prompt)
            if isinstance(result_json, list):
                res = [str(x) for x in result_json]
                self._query_expansion_cache[cache_key] = res
                return res
            if isinstance(result_json, dict) and "keywords" in result_json:
                res = [str(x) for x in result_json["keywords"]]
                self._query_expansion_cache[cache_key] = res
                return res
        except Exception as e:
            logger.debug(f"Query expansion fallback: {e}")

        # Basic fallback tokens
        tokens = [t.strip(",.()[]") for t in requirement.split() if len(t) > 2]
        res = list(set(tokens[:5]))
        self._query_expansion_cache[cache_key] = res
        return res

    def generate_grounded_explanation(
        self,
        job_title: str,
        job_description: str,
        requirements_summary: str,
        candidate_name: str,
        candidate_skills: str,
        experience_summary: str,
        evidence_chunks_text: str,
        skill_gaps_text: str,
        final_score: float,
        skill_score: float,
        experience_score: float,
        project_score: float,
        education_score: float,
    ) -> GroundedExplanation:
        """Generates an evidence-grounded explanation report citing specific chunk evidence."""
        prompt = (
            EXPLANATION_PROMPT.replace("{job_title}", job_title)
            .replace("{job_description}", job_description[:1500])
            .replace("{requirements_summary}", requirements_summary)
            .replace("{candidate_name}", candidate_name)
            .replace("{candidate_skills}", candidate_skills)
            .replace("{experience_summary}", experience_summary)
            .replace("{evidence_chunks_text}", evidence_chunks_text)
            .replace("{skill_gaps_text}", skill_gaps_text)
            .replace("{final_score}", str(round(final_score, 1)))
            .replace("{skill_score}", str(round(skill_score, 1)))
            .replace("{experience_score}", str(round(experience_score, 1)))
            .replace("{project_score}", str(round(project_score, 1)))
            .replace("{education_score}", str(round(education_score, 1)))
        )

        try:
            result_json = self._call_gemini_json(prompt, temperature=0.2)
            return GroundedExplanation(**result_json)
        except Exception as e:
            logger.warning(f"LLM explanation generation failed, using fallback report: {e}")
            return self._fallback_grounded_explanation(
                candidate_name=candidate_name,
                job_title=job_title,
                final_score=final_score,
                skill_gaps_text=skill_gaps_text,
            )

    # ---------------- Heuristic Fallbacks ----------------

    def _fallback_job_extraction(self, text: str) -> ExtractedJobData:
        lines = [line.strip() for line in text.split("\n") if line.strip()]
        title = lines[0] if lines else "Software Engineer"
        company = lines[1] if len(lines) > 1 and len(lines[1]) < 50 else None

        # Detect common technical skills in text
        skill_catalog = [
            ("Python", "language", True, "high"),
            ("FastAPI", "framework", True, "high"),
            ("Django", "framework", False, "medium"),
            ("PostgreSQL", "database", True, "high"),
            ("SQL", "database", True, "high"),
            ("Docker", "tool", True, "medium"),
            ("Kubernetes", "tool", False, "medium"),
            ("AWS", "cloud", False, "medium"),
            ("GCP", "cloud", False, "medium"),
            ("Git", "tool", True, "low"),
            ("REST APIs", "concept", True, "high"),
            ("TypeScript", "language", False, "medium"),
            ("React", "framework", False, "medium"),
        ]

        requirements: List[ExtractedRequirement] = []
        for name, cat, req, imp in skill_catalog:
            if re.search(rf"\b{re.escape(name)}\b", text, re.IGNORECASE):
                requirements.append(
                    ExtractedRequirement(
                        skill_name=name,
                        is_required=req,
                        importance=imp,
                        category=cat,
                    )
                )

        if not requirements:
            requirements.append(
                ExtractedRequirement(
                    skill_name="Python",
                    is_required=True,
                    importance="high",
                    category="language",
                )
            )

        return ExtractedJobData(
            title=title,
            company_name=company,
            summary=text[:300],
            requirements=requirements,
        )

    def _fallback_candidate_extraction(self, text: str) -> ExtractedCandidateProfile:
        email_match = re.search(r"[\w\.-]+@[\w\.-]+\.\w+", text)
        phone_match = re.search(r"\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}", text)

        email = email_match.group(0) if email_match else None
        phone = phone_match.group(0) if phone_match else None

        # Guess name from first non-empty line
        lines = [line.strip() for line in text.split("\n") if line.strip()]
        name = lines[0] if lines and len(lines[0]) < 60 else "Candidate"

        skill_catalog = [
            "Python",
            "FastAPI",
            "Django",
            "Flask",
            "PostgreSQL",
            "MySQL",
            "SQLite",
            "Docker",
            "Kubernetes",
            "AWS",
            "GCP",
            "Azure",
            "Git",
            "REST APIs",
            "GraphQL",
            "Redis",
            "Linux",
            "TypeScript",
            "JavaScript",
            "React",
            "Node.js",
            "PyTorch",
            "Machine Learning",
            "CI/CD",
        ]
        detected_skills = [
            s for s in skill_catalog if re.search(rf"\b{re.escape(s)}\b", text, re.IGNORECASE)
        ]

        return ExtractedCandidateProfile(
            name=name,
            email=email,
            phone=phone,
            summary=text[:250],
            skills=detected_skills,
            experience=[
                ExtractedExperience(
                    company="Previous Company",
                    role="Software Engineer",
                    duration="2+ years",
                    skills_used=detected_skills[:5],
                    highlights=["Engineered scalable software solutions and backend workflows."],
                )
            ],
            projects=[
                ExtractedProject(
                    name="Application Project",
                    description="Implemented backend architectures and API interfaces.",
                    technologies=detected_skills[:3],
                )
            ],
            education=[
                ExtractedEducation(
                    degree="Bachelor of Science",
                    institution="University",
                    year="2022",
                )
            ],
            certifications=[],
        )

    def _fallback_grounded_explanation(
        self, candidate_name: str, job_title: str, final_score: float, skill_gaps_text: str
    ) -> GroundedExplanation:
        fit = "strong" if final_score >= 80 else ("moderate" if final_score >= 60 else "weak")
        return GroundedExplanation(
            summary=(
                f"{candidate_name} scored {final_score:.1f}/100 for the {job_title} position. "
                f"Evaluation indicates a {fit} alignment with required competencies."
            ),
            overall_fit=fit,
            strengths=[],
            gaps=[],
            experience_analysis="Candidate possesses relevant background; verify depth during technical screen.",
            recruiter_recommendation=(
                "Advance to technical interview" if final_score >= 70 else "Review candidate portfolio"
            ),
        )


llm_client = LLMClient()
